#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    crisesweb-app:
        image: crisesweb
        external_links:
            - crisesweb-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - crisesweb-cassandra:cassandra
            - crisesweb-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/crisesweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    crisesweb-mysql:
        extends:
            file: mysql.yml
            service: crisesweb-mysql
    # Uncomment to have Cassandra working with the gateway
    # crisesweb-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: crisesweb-cassandra
    # crisesweb-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: crisesweb-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    crisesweb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: crisesweb-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
