version: '2'
services:
    crisesweb-elasticsearch:
        container_name: crisesweb-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/CrisesWeb/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
